<?php
return [
  'up'       => '{:eject_symbol:} {{text}}',
  'close'    => '{:stop_button:} {{text}}',
  'prev'     => '{:rewind:} {{name}}',
  'next'     => '{{name}} {:fast_forward:}',
  'first'    => '{:previous_track:} {{name}}',
  'last'     => '{{name}} {:next_track:}',
  'play'     => '{:arrow_forward:}',
  'fav_on'   => '{:star:}',
  'fav_off'  => '{:sparkles:}{:star:}{:sparkles:}',
  'refresh'  => '{{name}} {:arrows_counterclockwise:}',
  'reset'    => '{:arrows_counterclockwise:} {{name}}',
  'retry'    => '{:arrow_right_hook:} {{name}}',
  'ok'       => 'OK',
  'select0'  => '{{text}}',
  'select1'  => '{:green_circle:} {{text}}',
  'go'       => '{:arrow_forward:} {{text}}',
];
?>
