<?php
return [
  'up'       => '{:eject_symbol:} {{name}}',
  'prev'     => '{:rewind:} {{name}}',
  'next'     => '{{name}} {:fast_forward:}',
  'first'    => '{:previous_track:} {{name}}',
  'last'     => '{{name}} {:next_track:}',
  'play'     => '{:arrow_forward:}',
  'stop'     => '{:stop_button:}',
  'fav_on'   => '{:star:}',
  'fav_off'  => '{:sparkles:}{:star:}{:sparkles:}',
  'refresh'  => '{{name}} {:arrows_counterclockwise:}',
  'ok'       => 'OK',
  'select0'  => '{{text}}',
  'select1'  => '{:green_circle:} {{text}}',
];
?>
