<?php
return [
  'en' =>
  [
    'up'       => '{:eject_symbol:} {{hint}}',
    'prev'     => '{:rewind:} {{name}}',
    'next'     => '{{name}} {:fast_forward:}',
    'first'    => '{:previous_track:}',
    'last'     => '{{name}} {:next_track:}',
    'play'     => '{:arrow_forward:}',
    'stop'     => '{:stop_button:}',
    'fav_on'   => '{:star:}',
    'fav_off'  => '{:sparkles:}{:star:}{:sparkles:}',
    'quit'     => '{:x:}',
    'refresh'  => '{:arrows_counterclockwise:}',
    'ok'       => 'OK',
    'select0'  => '{{option}}',
    'select1'  => '{:green_circle:} {{option}}',
  ],
  'ru' =>
  [
    'up'       => '{:eject_symbol:} {{hint}}',
    'prev'     => '{:rewind:} {{name}}',
    'next'     => '{{name}} {:fast_forward:}',
    'first'    => '{:previous_track:}',
    'last'     => '{{name}} {:next_track:}',
    'play'     => '{:arrow_forward:}',
    'stop'     => '{:stop_button:}',
    'fav_on'   => '{:star:}',
    'fav_off'  => '{:sparkles:}{:star:}{:sparkles:}',
    'quit'     => '{:x:}',
    'refresh'  => '{:arrows_counterclockwise:}',
    'ok'       => 'OK',
    'select0'  => '{{option}}',
    'select1'  => '{:green_circle:} {{option}}',
  ],
];
?>
