<?php return [
  'game'     => '{:arrow_forward:} {{.}}',
  'up'       => '{:eject_symbol:} {{.}}',
  'close'    => '{:stop_button:} {{.}}',
  'open'     => '{{.}}',
  'prev'     => '{:rewind:} {{.}}',
  'next'     => '{{.}} {:fast_forward:}',
  'back'     => '{:arrow_backward:} {{.}}',
  'forward'  => '{{.}} {:arrow_forward:}',
  'first'    => '{:previous_track:} {{.}}',
  'last'     => '{{.}} {:next_track:}',
  'refresh'  => '{{.}} {:arrows_counterclockwise:}',
  'reset'    => '{:arrow_right_hook:} {{.}}',
  'retry'    => '{{.}} {:arrows_counterclockwise:}',
  'repeat'   => '{:repeat:} {{.}}',
  'change'   => '{{.}} {:keycap_asterisk:}',
  'ok'       => 'OK',
  'submit'   => '{{.}} {:record_button:}',
  'add'      => '{:new:} {{.}}',
  'create'   => '{:new:} {{.}}',
  'start'    => '{:arrow_forward:} {{.}}',
  'stop'     => '{:double_vertical_bar:} {{.}}',
  'clear'    => '{{.}} {:leftwards_arrow_with_hook:}',
  ###
  'list.open'   => '{{id}}:{{name}}',
  'list.select' => '
    {{#selected}}
      {:green_circle:}{:NBSP:}
    {{/selected}}
    {{name}}
  ',
  ###
  'fav_on'   => '{:star:}',
  'fav_off'  => '{:sparkles:}{:star:}{:sparkles:}',
];
?>
