<?php return [
  'play'     => '{:arrow_forward:} {{.}}',
  'up'       => '{:eject_symbol:} {{.}}',
  'close'    => '{:stop_button:} {{.}}',
  'open'     => '{{.}}',
  'prev'     => '{:rewind:} {{.}}',
  'next'     => '{{.}} {:fast_forward:}',
  'back'     => '{:arrow_backward:} {{.}}',
  'forward'  => '{{.}} {:arrow_forward:}',
  'first'    => '{:previous_track:} {{.}}',
  'last'     => '{{.}} {:next_track:}',
  'refresh'  => '{{.}} {:arrows_counterclockwise:}',
  'reset'    => '{:arrows_counterclockwise:} {{.}}',
  'retry'    => '{:arrow_right_hook:} {{.}}',
  'ok'       => 'OK',
  'add'      => '{:new:} {{.}}',
  'create'   => '{:new:} {{.}}',
  ###
  'listItem' => '{{id}}:{{name}}',
  ###
  'select0'  => '{{.}}',
  'select1'  => '{:green_circle:} {{.}}',
  'fav_on'   => '{:star:}',
  'fav_off'  => '{:sparkles:}{:star:}{:sparkles:}',
];
?>
