<?php return [
  'play'     => '{:arrow_forward:} {{.}}',
  'up'       => '{:eject_symbol:} {{.}}',
  'close'    => '{:stop_button:} {{.}}',
  'open'     => '{{.}}',
  'prev'     => '{:rewind:} {{.}}',
  'next'     => '{{.}} {:fast_forward:}',
  'back'     => '{:arrow_backward:} {{.}}',
  'forward'  => '{{.}} {:arrow_forward:}',
  'first'    => '{:previous_track:} {{.}}',
  'last'     => '{{.}} {:next_track:}',
  'refresh'  => '{{.}} {:arrows_counterclockwise:}',
  'reset'    => '{:arrow_right_hook:} {{.}}',
  'retry'    => '{:arrows_counterclockwise:} {{.}}',
  'repeat'   => '{{.}} {:repeat:}',
  'ok'       => 'OK',
  'add'      => '{:new:} {{.}}',
  'create'   => '{:new:} {{.}}',
  'start'    => '{:arrow_forward:} {{.}}',
  'stop'     => '{:double_vertical_bar:} {{.}}',
  'clear'    => '{{.}} {:leftwards_arrow_with_hook:}',
  ###
  'listItem' => '{{id}}:{{name}}',
  'select'   => '{{#v}}{:green_circle:}{{/v}} {{x}}',
  ###
  'fav_on'   => '{:star:}',
  'fav_off'  => '{:sparkles:}{:star:}{:sparkles:}',
];
?>
